# Generated by Django 4.2.10 on 2024-02-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registrationpage', '0002_alter_register_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Phone_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
